version: "3"
services:
  database:
    container_name: postgres-postgresql
    image: postgres:12-alpine
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"

  app:
    container_name: sample_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - default





volumes:
  postgres-data: